# Generated by Django 5.0.6 on 2024-10-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_usefullink_alter_project_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.AlterModelOptions(
            name='usefullink',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'сайты'},
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на демонстрацию'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='project',
            name='sections',
            field=models.ManyToManyField(blank=True, to='projects.section', verbose_name='Разделы'),
        ),
    ]
