# Generated by Django 5.0.6 on 2024-11-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner_alter_project_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
