# Generated by Django 5.0.6 on 2024-11-24 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='project_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
