# Generated by Django 5.0.6 on 2024-11-28 12:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sections',
            field=models.ManyToManyField(blank=True, to='projects.section', verbose_name='Категории'),
        ),
    ]
