# Generated by Django 5.0.6 on 2024-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myself_short',
            field=models.CharField(blank=True, max_length=200, verbose_name='О себе коротко'),
        ),
    ]
