# Generated by Django 5.0.6 on 2024-11-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_note_profile_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Подпись')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.profile')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'фотографии',
            },
        ),
    ]
