# Generated by Django 5.0.6 on 2024-11-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Подпись')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.profile')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'видео',
            },
        ),
    ]
